services:
  # Backend - API REST FastAPI
  - type: web
    name: legalassista
    env: python
    plan: free
    region: oregon
    rootDir: ./backend
    buildCommand: pip install -r backend/requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: legalassista-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: legalassista-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://legalassista-frontend.onrender.com
      - key: OPENAI_API_KEY
        sync: false # Debe ser configurado manualmente
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false # Debe ser configurado manualmente
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false # Debe ser configurado manualmente

  # Frontend - React/Vite
  - type: web
    name: legalassista-frontend
    env: static
    plan: free
    region: oregon
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://legalassista.onrender.com
      - key: VITE_WEBSOCKET_URL
        value: wss://legalassista.onrender.com/ws

# Base de datos PostgreSQL
databases:
  - name: legalassista-db
    plan: free
    region: oregon

# Redis para WebSockets y cache
services:
  - type: redis
    name: legalassista-redis
    plan: free
    region: oregon
    ipAllowList: []

# Ambiente de producción - Las variables serán configuradas en el dashboard de Render
envs:
  - key: SECRET_KEY
    generateValue: true # Genera una clave secreta automáticamente
    description: "Clave secreta para JWT"
  
  - key: OPENAI_API_KEY
    sync: false
    description: "Tu clave de API de OpenAI para integraciones de IA"
  
  - key: MERCADOPAGO_ACCESS_TOKEN
    sync: false
    description: "Token de acceso para integraciones de MercadoPago"
  
  - key: DATABASE_URL
    fromDatabase:
      name: legalassista_db
      property: connectionString
    description: "URL de conexión a la base de datos PostgreSQL"
  
  - key: MAIL_USERNAME
    sync: false
    description: "Usuario de correo para envío de emails"
  
  - key: MAIL_PASSWORD
    sync: false
    description: "Contraseña de correo para envío de emails"
  
  - key: MAIL_FROM
    sync: false
    description: "Dirección de correo remitente"
  
  - key: MAIL_SERVER
    sync: false
    description: "Servidor SMTP para envío de emails"
  
  - key: FRONTEND_URL
    value: "https://legalassista-frontend.onrender.com"
    description: "URL del frontend para redirecciones CORS" 