"""Add caso_id FK to documentos

Revision ID: 3e1661d2a6b2
Revises: 
Create Date: 2025-05-20 17:01:12.888652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1661d2a6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('ruta', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('numero_ley', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('subcategoria', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.drop_index('ix_metricauso_id', table_name='metricauso')
    op.drop_table('metricauso')
    op.drop_index('ix_feedbackusuario_id', table_name='feedbackusuario')
    op.drop_table('feedbackusuario')
    op.drop_index('ix_legal_documents_category', table_name='legal_documents')
    op.drop_index('ix_legal_documents_document_type', table_name='legal_documents')
    op.drop_index('ix_legal_documents_id', table_name='legal_documents')
    op.drop_index('ix_legal_documents_issue_date', table_name='legal_documents')
    op.drop_index('ix_legal_documents_reference_number', table_name='legal_documents')
    op.drop_index('ix_legal_documents_subcategory', table_name='legal_documents')
    op.drop_index('ix_legal_documents_title', table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index('ix_calificacion_id', table_name='calificacion')
    op.drop_table('calificacion')
    op.drop_index('ix_documento_id', table_name='documento')
    op.drop_table('documento')
    op.add_column('facturas', sa.Column('mercadopago_id', sa.String(length=100), nullable=True))
    op.add_column('facturas', sa.Column('mercadopago_status', sa.String(length=50), nullable=True))
    op.add_column('facturas', sa.Column('mercadopago_external_reference', sa.String(length=100), nullable=True))
    op.add_column('facturas', sa.Column('mercadopago_payment_id', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_registro')
    op.drop_column('facturas', 'mercadopago_payment_id')
    op.drop_column('facturas', 'mercadopago_external_reference')
    op.drop_column('facturas', 'mercadopago_status')
    op.drop_column('facturas', 'mercadopago_id')
    op.create_table('documento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contenido', sa.TEXT(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('caso_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documento_id', 'documento', ['id'], unique=False)
    op.create_table('calificacion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('puntuacion', sa.FLOAT(), nullable=False),
    sa.Column('comentario', sa.TEXT(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('referencia_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calificacion_id', 'calificacion', ['id'], unique=False)
    op.create_table('legal_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('issue_date', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('content_vector', sa.TEXT(), nullable=True),
    sa.Column('keywords', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subcategory', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_documents_title', 'legal_documents', ['title'], unique=False)
    op.create_index('ix_legal_documents_subcategory', 'legal_documents', ['subcategory'], unique=False)
    op.create_index('ix_legal_documents_reference_number', 'legal_documents', ['reference_number'], unique=False)
    op.create_index('ix_legal_documents_issue_date', 'legal_documents', ['issue_date'], unique=False)
    op.create_index('ix_legal_documents_id', 'legal_documents', ['id'], unique=False)
    op.create_index('ix_legal_documents_document_type', 'legal_documents', ['document_type'], unique=False)
    op.create_index('ix_legal_documents_category', 'legal_documents', ['category'], unique=False)
    op.create_table('feedbackusuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('calificacion', sa.INTEGER(), nullable=True),
    sa.Column('comentario', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedbackusuario_id', 'feedbackusuario', ['id'], unique=False)
    op.create_table('metricauso',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('tipo_accion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('detalles', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metricauso_id', 'metricauso', ['id'], unique=False)
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
